version: '3.7'

services:
  database:
    image: mongo
    container_name: database_container
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - manogo_data:/data/mongo

  redis_database:
    image: redis
    container_name: redis_container
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data/redis

  app:
    build: .
    ports:
      - ${API_PORT}:3000
    volumes:
      - .:/home/service
    depends_on:
      - database
      - redis_database

volumes:
  manogo_data:
  redis_data:
